### ISSUE TITLE
is Asus Crosshair VII Hero?

### ISSUE THREAD

**Issue by wintry** [ainsleyclark/ryzentosh#1]
Asus Crosshair VII Hero is x470
or Asus Crosshair VIII Hero
Asus Crosshair VIII Hero is x570

**Comment by ainsleyclark** [comment]
Sorry I'm not so sure I understand your question, this repo is for `ASUS Crosshair VII Hero X570`

**Comment by wintry** [comment]
i mean you might use wrong Greek numerals
 Crosshair VII Hero is x470，
and x570 is  Crosshair VIII Hero

**Comment by ainsleyclark** [comment]
There isn't a question here?
