### ISSUE TITLE
Bluetooth issues

### ISSUE THREAD

**Issue by williamcorney** [ainsleyclark/ryzentosh#3]
Hello, I came across a post of yours on Tony Mac.

Did you ever resolve the problem of the Bluetooth disconnect in every two hours? I am having very similar problems and have tried very similar things. I’ve got a Fenvi t919 on order .  Did you end up getting and did it help ?

I would’ve written to you on the other forum, but the admins there are a nightmare .  I somehow got banned for mentioning proxmox template 

my specs are 
GA-A320M-S2H
Ryzen 7 2700
RX570 8GB
32GB RAM ( tried disabling xmp)
Ventura 13.6.6
Opencore 0.99
Bare metal currently ( though tried proxmox and still issues)

**Comment by ainsleyclark** [comment]
Hi there,

Bluetooth on the Fenvi T919 I've never had a problem with, plug and play. So you should be good to go with that.

**Comment by williamcorney** [comment]
Thankyou.  

Can I confirm tho that you did have a problem with a prior Fenvi card you were using and whether it was directly changing to the T919 that resolved the problem or other factors?  

I've tried just about everything and anything else I can think of with kexts , acpi files.  I even like you made up a usb cable so I could plug the usb into a different controller on my motherboard.

Its the final piece de resistance between me having a happy fully working Mac and not.
